-- 코드를 작성해주세요
SELECT
    E1.ID,
    IFNULL(E2.COUNT, 0) AS CHILD_COUNT
FROM
    ECOLI_DATA E1 LEFT JOIN (SELECT PARENT_ID, COUNT(PARENT_ID) AS COUNT FROM ECOLI_DATA GROUP BY PARENT_ID) E2
    ON E1.ID = E2.PARENT_ID
ORDER BY
    E1.ID ASC;
