-- 코드를 작성해주세요
SELECT
    COUNT(*) AS FISH_COUNT,
    NAME.FISH_NAME AS FISH_NAME
FROM
    FISH_INFO FISH JOIN FISH_NAME_INFO NAME ON FISH.FISH_TYPE = NAME.FISH_TYPE
GROUP BY
    NAME.FISH_NAME
ORDER BY
    FISH_COUNT DESC;