-- 코드를 작성해주세요
SELECT
    I.ID,
    N.FISH_NAME,
    F.LENGTH
FROM
    (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) F
    JOIN FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE
    JOIN FISH_INFO I ON (I.FISH_TYPE = N.FISH_TYPE AND I.LENGTH = F.LENGTH)
ORDER BY
    I.ID ASC;