-- 코드를 작성해주세요
SELECT
    D.DEPT_ID,
    D.DEPT_NAME_EN,
    E.AVG_SAL
FROM
    HR_DEPARTMENT D JOIN (SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL FROM HR_EMPLOYEES GROUP BY DEPT_ID) E
    ON D.DEPT_ID = E.DEPT_ID
ORDER BY
    AVG_SAL DESC;